### ISSUE TITLE
US-33: As an admin, I want to be able to revoke application access privileges to specific individuals, so that they may not use the system.

### ISSUE THREAD

**Issue by wbroome14** [LukaASoban/Child-Monitoring-System#11]
## **Task Details**
- [ ] Add admin access to user accounts via search function
- [ ] Add button to change access privileges.
- [ ] Code button so that it updates the database.
## **Acceptance Criteria**
Given: A registered admin on a user account screen.
When: The access button is modified.
Then: The user loses access to the system.
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
## **Failure Criteria**
User access privileges are not changed.
