### ISSUE TITLE
US-34: As an admin, I want to be able to remove a child from the system, so that I can keep the system consistent with actual class roster.

### ISSUE THREAD

**Issue by wbroome14** [LukaASoban/Child-Monitoring-System#12]
## **Task Details**
- [ ] Add child list to admin view of user profile.
- [ ] Add delete button to children so they can be removed.
- [ ] Code button and database.
## **Acceptance Criteria**
Given: A registered admin on the search screen.
When: A user is selected and a child is deleted.
Then: The child is removed from the system.
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
## **Failure Criteria**
Child is not removed from the database.
