### ISSUE TITLE
As a registered user, I want to be able to change information in my profile, so that I can be sure my profile is correct and up to date. 5

### ISSUE THREAD

**Issue by kstrange62** [LukaASoban/Child-Monitoring-System#13]
## **Task Details**
- [ ] Code profile screen.
- [ ] Create profile screen.
- [ ] Add back-end logic to set information in the database.
## **Acceptance Criteria**
Given: A registered user on the profile screen.
When: The change profile options is selected.
Then: The system changes the information and sets it into the database.
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
