### ISSUE TITLE
As a parent, I want to be able to create a profile, so that the system will remember my information when I login. 4

### ISSUE THREAD

**Issue by kstrange62** [LukaASoban/Child-Monitoring-System#14]
## **Task Details**
- [x] Code registration screen.
- [x] Design registration screen.
- [x] Allow user to specify institution.
## **Acceptance Criteria**
Given: A unregistered user on the registration screen.
When: The register button is pressed, and all information has been filled out.
Then: The system adds the information into the database.
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
