### ISSUE TITLE
As a daycare employee, I want to be able to create a profile as an employee, so that the system can save my information and provide me with employee privileges. 15

### ISSUE THREAD

**Issue by kstrange62** [LukaASoban/Child-Monitoring-System#15]
## **Task Details**
- [x] Code registration screen.
- [x] Create registration screen.
- [x] Add back-end logic to set information in the database.
## **Acceptance Criteria**
Given: As unregistered user on the registration screen.
When: The register button is pressed, and all information has been filled out.
Then: The system changes the information and adds it into the database.
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
