### ISSUE TITLE
US-26: As a daycare employee, I want to be able to group children by age groups or classes, so that I can have an organized way of viewing the children.

### ISSUE THREAD

**Issue by mgb519** [LukaASoban/Child-Monitoring-System#21]
## **Task Details**
- [ ] Code structure which allows for custom groups of children
- [ ] Add back-end logic to modify information from the database.
- [ ] Add interface for employees to use in app to create children groups
## **Acceptance Criteria**
Given: A registered employee on the class page
When: The employee adds children to create their roster
Then: The class roster is updated
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
## **Failure Criteria**
The class roster is not stored correctly
The class roster is not updated when the user attempts to modify it
