### ISSUE TITLE
US-3. As a parent, I want to be able to view the room my child is in at a given time, so that I can ensure my child is safe.

### ISSUE THREAD

**Issue by swodajo3** [LukaASoban/Child-Monitoring-System#22]
## **Task Details**
- [x] Add parent access to map
- [x] Design map screen to display what room child is in
- [x] Code display to update map in real time
## **Acceptance Criteria**
Given: A registered parent on the map screen
When: The the child is in a certain room
Then: Parent can identify where their child is on the map
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
## **Failure Criteria**
Parent cannot see what room their child is in.
Child is not listed in the correct room.
