### ISSUE TITLE
US-19. As a daycare employee, I want to be able to view a map of the building with every child’s location at any given time, so that I can ensure they are safe.

### ISSUE THREAD

**Issue by swodajo3** [LukaASoban/Child-Monitoring-System#23]
## **Task Details**
- [x] Add daycare employee access to map
- [x] Design map screen to display what rooms children are in
- [x] Code display to update map in real time
## **Acceptance Criteria**
Given: A registered employee on the map screen
When: The the child is in a certain room
Then: daycare employee can identify where the children are on the map
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
## **Failure Criteria**
Daycare employee cannot see what room a child is in.
Child is not listed in the correct room.
