### ISSUE TITLE
US-24. As a daycare employee, I want to be able to assign children to different rooms at various times of the day and be notified when they are not at the assigned locations, so that the children do not get lost in the facility or miss classes.

### ISSUE THREAD

**Issue by swodajo3** [LukaASoban/Child-Monitoring-System#24]
## **Task Details**
- [x] Add daycare worker access to child schedule
- [x] Update child with real time location
- [x] Notify daycare worker when child is not at assigned location
## **Acceptance Criteria**
Given: A registered daycare employee viewing any screen
When: A child is in the wrong location
Then: The employee is notified that the child is in the wrong place
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
## **Failure Criteria**
Child cannot be assigned to room
Notifications cannot be created.
