### ISSUE TITLE
US-29. As an admin, I want to be able to designate rooms to monitor, so that the important locations are monitored.

### ISSUE THREAD

**Issue by swodajo3** [LukaASoban/Child-Monitoring-System#25]
## **Task Details**
- [x] Add interface to designate rooms
- [x] Link raspberry pi sensors to the system
- [x] Make rooms track bracelets from raspberry pi sensor
## **Acceptance Criteria**
Given: A registered parent on the map screen
When: The admin presses the add room button and places a room on the map, and hooks it up to a sensor
Then: The room is set up to be monitored
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
## **Failure Criteria**
Admin cannot designate rooms correctly
Sensors are not connected to rooms
