### ISSUE TITLE
US-10: As a parent, I would like to be able to report a complaint or bug in the system so that I can help improve the system if I am having any problems.

### ISSUE THREAD

**Issue by LukaASoban** [LukaASoban/Child-Monitoring-System#4]
## **Task Details**
- [x] Create error report screen
- [x] Allow parents to access error report
- [x] Code app to send error reports to database
## **Acceptance Criteria**
Given: A parent using the app
When: They go to the error report screen
Then: The parent can send an error report
## **Done Criteria**
Design is accepted by all group members, and all unit tests are passed.
## **Failure Criteria**
The error report screen cannot be accessed
The error reports do not send correctly to the database
