### ISSUE TITLE
As a registered user I want to log into the app. #2

### ISSUE THREAD

**Issue by kstrange62** [LukaASoban/Child-Monitoring-System#7]
##  **Task Details**
- [x] Code login screen.
- [x] Create login screen.
- [x] Add login button.
- [x] Add register button.
- [x] Add logo.
## **Acceptance Scenerios**
Given: A registered user is in the system.
When: The user enters the correct id and password.
Then: The user is taken to their dashboard page.
## **Done Criteria**
Customer has approved UI design, and passes all tests.

**Comment by kstrange62** [comment]
Needs to be connected to the database and registration screen.

**Comment by kstrange62** [comment]
Logo/name still being designed.
